# Project: Projeto_Empresa
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Empregado.o Gestor.o main.o
LINKOBJ  = Empregado.o Gestor.o main.o
LIBS     = -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib" -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Projeto_Empresa.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\Users\Guilherme Rodrigues\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Empregado.o: Empregado.cpp
	$(CPP) -c Empregado.cpp -o Empregado.o $(CXXFLAGS)

Gestor.o: Gestor.cpp
	$(CPP) -c Gestor.cpp -o Gestor.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
