# Project: Project_3
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Ingresso.o Vip.o Normal.o CamaroteInferior.o CamaroteSuperior.o
LINKOBJ  = main.o Ingresso.o Vip.o Normal.o CamaroteInferior.o CamaroteSuperior.o
LIBS     = -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib" -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project_3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\Users\Guilherme Rodrigues\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Ingresso.o: Ingresso.cpp
	$(CPP) -c Ingresso.cpp -o Ingresso.o $(CXXFLAGS)

Vip.o: Vip.cpp
	$(CPP) -c Vip.cpp -o Vip.o $(CXXFLAGS)

Normal.o: Normal.cpp
	$(CPP) -c Normal.cpp -o Normal.o $(CXXFLAGS)

CamaroteInferior.o: CamaroteInferior.cpp
	$(CPP) -c CamaroteInferior.cpp -o CamaroteInferior.o $(CXXFLAGS)

CamaroteSuperior.o: CamaroteSuperior.cpp
	$(CPP) -c CamaroteSuperior.cpp -o CamaroteSuperior.o $(CXXFLAGS)
