# Project: Exercicio_1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Administrativo.o Tecnico.o Assistente.o Gerente.o Funcionario.o
LINKOBJ  = main.o Administrativo.o Tecnico.o Assistente.o Gerente.o Funcionario.o
LIBS     = -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib" -L"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Users/Guilherme Rodrigues/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Exercicio_1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\Users\Guilherme Rodrigues\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Administrativo.o: Administrativo.cpp
	$(CPP) -c Administrativo.cpp -o Administrativo.o $(CXXFLAGS)

Tecnico.o: Tecnico.cpp
	$(CPP) -c Tecnico.cpp -o Tecnico.o $(CXXFLAGS)

Assistente.o: Assistente.cpp
	$(CPP) -c Assistente.cpp -o Assistente.o $(CXXFLAGS)

Gerente.o: Gerente.cpp
	$(CPP) -c Gerente.cpp -o Gerente.o $(CXXFLAGS)

Funcionario.o: Funcionario.cpp
	$(CPP) -c Funcionario.cpp -o Funcionario.o $(CXXFLAGS)
